### ISSUE TITLE
The Dark Mod

### ISSUE THREAD

**Issue by nbohr1more** [DanielGibson/dhewm3-base-mods#1]
Hi Daniel

Serpentine from The Dark Mod has been working on merging our sources with Dhewm3 but has been tied up (MIA?) recently. I wonder if you'd be willing to look at the current WIP code and assist with this?

Thanks,

nbohr1more

**Comment by DanielGibson** [comment]
"Our sources"? Are you from the TDM Team?
If TDM would want to switch to dhewm3 I'd be willing to help (as much as my spare time allows).
If not I don't think porting TDM to dhewm3 is worthwhile because I guess that maintaining that port would be hard (and even harder over time, when TDM does more changes to the engine).

(I have no clue what state the TDM source is in, never looked at it, but I heard that it neither uses OpenAL on all platforms nor is it 64bit clean, so switching to dhewm3 would be a big improvement.)

**Comment by nbohr1more** [comment]
I am a promoter for The Dark Mod and I have occasionally spoken on their behalf. This is sort of an independent initiative to re-invigorate project morale. So many folks in the inner-sanctum have brushed-off this merge project as a "far off pipe-dream" that I felt I should do a little leg-work to get an outside opinion. 

Thus far, the team has already discussed the merits of moving to Dhewm3 and has agreed that it's a worthwhile endeavor. Serpentine was given license to go ahead with his porting work on the condition that he merge his work cleanly to the trunk in one big commit. I cant speak to why these are the terms other than perhaps it's due to bad experiences during our project to add LOD and Procedural Content generation to the mod.

Here is a link to our latest SVN sources if you'd like to take a peek:

http://www.thedarkmod.com/downloads/

Since you were kind enough to reply and possibly extend the offer to assist, I will coordinate with the team to see if I a Git can be made since that's probably your preferred way to work (don't know why we don't have one already...)

**Comment by DanielGibson** [comment]
Probably the best way to do it would be something like:
1. Merge TDM Engine changes into a dhewm3 branch
2. The same for the game code - it may be easier to do it the other way round though (take the TDM game code and merge the dhewm3 changes)
3. Commit all this to the TDM SVN repo (as they want it on a single commit anyway)

Serpentines probably did a lot of this work already and probably could be used.

**Comment by ghost** [comment]
I've been investigating idTech4 for an indie project I'm trying to start up. I came across both dhewm3 and TDM as a result. From what I can tell in the forums - there's been talk of a merge for quite some time. Has any progress been made on it or has it been all talk up until this point? Out of curiosity what features does TDM have now that aren't present in dhewm?

Thanks!

A.

**Comment by nbohr1more** [comment]
The Dark Mod has a couple of unique features:

Object LOD: you can define entities that swap models for higher or lower poly versions based on distance. You can also set LOD_BIAS arguments to ensure that models of certain quality only show for certain Object Detail settings. Finally you can set hide distance to simply make models disappear if far enough away.

SEED: A procedural content generator that can place models randomly in pre-defined areas. It also can optimize existing geometry by combining entities and models.

Sound specific portals for better environmental audio control.

Func_portals that can close their associated portal at a LOD distance.

Ambient light rendering has been broken into it's own dedicated shader.

Dynamic ambient light controlled via location entities.

Savegame compression.

In-game mission downloader.

(I think 7318's HL2 skybox code is pending inclusion to Dhewg3 but we've already got it.)

The ones listed below are more tailored for our game but could be used for other similar games (RPG's etc):

A Lightgem visibility system where AI can detect you with various degrees of accuracy depending on your light level

Systems for igniting and extinguishing flames

More advanced AI with detection algorithms that take changes to the environment into account

Improved mantling including the ability to mantle onto moving objects

Frob highlighting and object rotation controls

A sword combat system akin to Mount and Blade's implementation.

Swimmable water.

**Comment by nbohr1more** [comment]
Closing this forgotten issue. 

The desirable Dhewm3 changes were cherry-picked by Greebo during the 2.05 development cycle then merged to trunk for the TDM 2.06 release. 

Someday I will have to convince Stgatilov and Cabalistic to port some TDM improvements as pull requests for this project.
